"use client";
import {useState,useEffect,useRef} from 'react';
import {Music2,Search,Copy,ArrowUpRight,SlidersHorizontal,Plus,X,Check,ChevronLeft,ChevronRight,Trash2,Pencil,Disc3,Headphones,LoaderCircle} from 'lucide-react';
import {youtubeUrl} from './youtube-url';
import songReferences from './song-references.json';
type SongReference={artist:string;url:string;note:string;clip:string;segmentUrl?:string;segmentLabel?:string;label?:string};
const references:Record<string,SongReference>=songReferences;
type Song={id:string;title:string;artist:string;hasLyrics?:boolean;lyrics?:string;youtube_url?:string|null;note?:string|null};
export default function Home(){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[songs,setSongs]=useState<Song[]>([]),[total,setTotal]=useState(0),[stats,setStats]=useState({total:0,artists:0,ready:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,refresh]=useState(0),[admin,setAdmin]=useState(false),[selected,setSelected]=useState<Song|null>(null),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState(''),[editing,setEditing]=useState<Song|null>(null),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[font,setFont]=useState(18);
 const [chosenArtist,setChosenArtist]=useState(''),[artistList,setArtistList]=useState<{name:string;count:number}[]>([]);
 const [loginPassword,setLoginPassword]=useState(''),[loginError,setLoginError]=useState(''),[loginBusy,setLoginBusy]=useState(false);
 const knownReference=selected?references[selected.title+'|'+selected.artist]:undefined;
 const playbackUrl=youtubeUrl(selected?.youtube_url??knownReference?.url??'');
 const matchesKnown=playbackUrl===youtubeUrl(knownReference?.url);
 const reference:SongReference|undefined=playbackUrl?{artist:matchesKnown?knownReference!.artist:selected?.artist||'',url:playbackUrl,note:selected?.note??(matchesKnown?knownReference!.note:''),clip:'',label:matchesKnown?(knownReference!.note.includes('改詞')||knownReference!.note.includes('現場改編')?'播放此版本':'播放原唱'):'播放 YouTube'}:undefined;
 const cache=useRef(new Map<string,Song>()),dialog=useRef<HTMLDialogElement>(null),editor=useRef<HTMLDialogElement>(null),loginDialog=useRef<HTMLDialogElement>(null),request=useRef(0);
 useEffect(()=>{const ac=new AbortController(); const timer=setTimeout(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/songs?q=${encodeURIComponent(query)}&artist=${encodeURIComponent(chosenArtist)}&filter=${filter}&page=${page}`,{signal:ac.signal});if(!r.ok)throw Error('暫時無法載入歌曲，請稍後重試');const data=await r.json() as {songs:Song[];total:number;stats:typeof stats;artists:{name:string;count:number}[]};setSongs(data.songs.map(s=>({...s,artist:s.artist.replace(/^PK主題[：:]\s*/,'')})));setTotal(data.total);setArtistList(data.artists||[]);setStats({...data.stats,ready:data.stats?.ready||0})}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{if(!ac.signal.aborted)setLoading(false)}},query?180:0);return()=>{clearTimeout(timer);ac.abort()}},[query,filter,page,revision,chosenArtist]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)},[toast]);
 async function mutation(data:any){
 const send=()=>fetch('/api/songs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
 const r=await send();if(r.status===401){setAdmin(false);setLoginPassword('');setLoginError('登入已逾期，請重新登入後再儲存。');loginDialog.current?.showModal();throw Error('請先重新登入，再按一次儲存。')}
 const b=await r.json() as {error?:string;ok?:boolean};if(!r.ok)throw Error(b.error||'儲存失敗');return b;
 }
 async function enterAdmin(){if(admin)return;try{const r=await fetch('/api/session',{cache:'no-store'});const s=await r.json() as {authenticated?:boolean};if(s.authenticated){setAdmin(true);return}}catch{}setLoginPassword('');setLoginError('');loginDialog.current?.showModal()}
 async function login(e:React.FormEvent){e.preventDefault();setLoginBusy(true);setLoginError('');try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:loginPassword})});const result=await r.json() as {error?:string};if(!r.ok){setLoginError(result.error||'登入失敗');return}setLoginPassword('');setAdmin(true);loginDialog.current?.close()}catch{setLoginError('連線失敗，請稍後再試')}finally{setLoginBusy(false)}}
 async function open(s:Song){const seq=++request.current;setSelected(s);setDetailError('');dialog.current?.showModal();const cached=cache.current.get(s.id);if(cached){setSelected(cached);setDetailLoading(false);return}setDetailLoading(true);try{const r=await fetch('/api/songs?id='+encodeURIComponent(s.id));if(!r.ok)throw Error('歌詞載入失敗，請重試');const data=await r.json() as Song;data.artist=data.artist.replace(/^PK主題[：:]\s*/,'');cache.current.set(s.id,data);if(seq===request.current)setSelected(data)}catch(e:any){if(seq===request.current)setDetailError(e.message)}finally{if(seq===request.current)setDetailLoading(false)}}
 function close(){request.current++;dialog.current?.close();setSelected(null)}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setToast('已複製到剪貼簿')}catch{setToast('複製失敗，請選取文字手動複製')}}
 function edit(s?:Song){setEditing(s?{...s,youtube_url:s.youtube_url??references[s.title+'|'+s.artist]?.url??'',note:s.note??references[s.title+'|'+s.artist]?.note??''}:{id:'',title:'',artist:'',lyrics:'',youtube_url:'',note:''});editor.current?.showModal()}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await mutation(editing);cache.current.clear();editor.current?.close();dialog.current?.close();setSelected(null);setEditing(null);refresh(x=>x+1);setToast('歌曲已儲存')}catch(e:any){setToast(e.message)}finally{setBusy(false)}}
 async function remove(s:Song){if(!confirm(`確定刪除「${s.title}」？`))return;setBusy(true);try{await mutation({action:'delete',id:s.id});cache.current.delete(s.id);close();refresh(x=>x+1);setToast('歌曲已刪除')}catch(e:any){setToast(e.message)}finally{setBusy(false)}}
 async function seed(){setBusy(true);try{await mutation({action:'seed'});refresh(x=>x+1);setToast('已加入示範歌曲，你可以自行編輯')}catch(e:any){setToast(e.message)}finally{setBusy(false)}}
 const visible=songs;
 return <><header><a className="brand" href="/"><span className="brand-icon"><Music2 size={23}/></span><span>PK曲庫</span></a><nav><button className={!admin?'nav-active':''} onClick={()=>setAdmin(false)}>探索歌曲</button><button className={admin?'nav-active':''} onClick={enterAdmin}><SlidersHorizontal size={15}/> 歌曲管理</button></nav><span className="header-note" role="status"><span style={{background:error?"#ef9a9a":loading?"#8998b2":"#72b98b"}}/> {error?"連線失敗":loading?"連線中…":"連線成功"}</span></header>
 <main>
 <section className="library"><div className="section-top"><div><h2>{admin?'歌曲管理':'查看歌庫'}<span> / {total}</span></h2></div>{admin?<button className="primary" onClick={()=>edit()}><Plus size={17}/> 新增歌曲</button>:<span className="section-hint"><Headphones size={16}/> 點選歌曲可查看歌詞</span>}</div>
 {admin&&<div className="admin-note">在這裡新增歌名、歌手與歌詞，儲存後即可在歌庫查詢。歌曲資料會保存在後端。</div>}
 <div className="collection-layout"><aside className="artist-panel"><div className="artist-panel-heading">歌手<span>{artistList.length}</span></div><div className="artist-options" aria-label="選擇歌手"><button className={!chosenArtist?'chosen':''} aria-pressed={!chosenArtist} onClick={()=>{setChosenArtist('');setQuery('');setPage(0)}}><span>全部歌手</span><small>{stats.total}</small></button>{artistList.map(a=><button key={a.name} className={chosenArtist===a.name?'chosen':''} aria-pressed={chosenArtist===a.name} onClick={()=>{setChosenArtist(a.name);setQuery('');setPage(0)}}><span>{a.name}</span><small>{a.count}</small></button>)}</div></aside><div className="collection-results">{chosenArtist&&<div className="artist-selection"><h3>{chosenArtist}</h3><button onClick={()=>{setChosenArtist('');setPage(0)}} aria-label="清除歌手篩選"><X size={15}/></button></div>}
 <div className="search-box"><Search size={21}/><input aria-label="搜尋歌曲或歌手" placeholder={chosenArtist?`搜尋 ${chosenArtist} 的歌曲…`:'搜尋歌曲或歌手…'} value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/>{query?<button aria-label="清除搜尋" onClick={()=>{setQuery('');setPage(0)}}><X size={18}/></button>:null}</div>
 <div className="filter-row"><div className="filters">{[['all','全部歌曲'],['lyrics','有歌詞']].map(([v,label])=><button key={v} className={filter===v?'active':''} onClick={()=>{setFilter(v);setPage(0)}}>{label}</button>)}</div><span className="result-count" aria-live="polite">{loading?'搜尋中…':`${total} 首搜尋結果`}</span></div>
 {error?<div className="empty"><p>{error}</p><button className="primary" onClick={()=>refresh(x=>x+1)}>重新載入</button></div>:loading?<div className="song-grid">{Array.from({length:12},(_,i)=><div className="skeleton" key={i}/>)}</div>:visible.length?<div className={admin?"song-grid management-list":"song-grid"}>{visible.map((s,i)=><article className="song-card" key={s.id}><button className="song-main" onClick={()=>open(s)}><span className="song-text"><strong>{s.title}</strong><small>{s.artist}</small></span><ArrowUpRight className="card-arrow" size={17}/></button><div className="card-bottom"><span className={s.hasLyrics?'lyrics-badge':'pending-badge'}><span/>{s.hasLyrics?'歌詞已收錄':'待加入歌詞'}</span><div><button aria-label={`複製 ${s.title}`} onClick={()=>copy(s.title+' - '+s.artist)}><Copy size={15}/></button></div></div></article>)}</div>:<div className="empty"><Disc3 size={38}/><h3>{query?'沒有找到這首歌':stats.total?'目前沒有符合的歌曲':'從第一首歌開始'}</h3><p>{query?'換個歌名或歌手試試看。':'新增你的歌曲與歌詞，建立專屬歌庫。'}</p>{!stats.total&&!query&&<div className="empty-actions"><button className="primary" onClick={()=>edit()}><Plus size={16}/> 新增歌曲</button></div>}</div>}
 {total>24&&<div className="pagination"><button aria-label="上一頁" disabled={page===0||loading} onClick={()=>setPage(x=>x-1)}><ChevronLeft size={17}/></button><span>{page+1} / {Math.ceil(total/24)}</span><button aria-label="下一頁" disabled={(page+1)*24>=total||loading} onClick={()=>setPage(x=>x+1)}><ChevronRight size={17}/></button></div>}
 </div></div></section></main>
 <dialog ref={dialog} className="lyrics-dialog" onCancel={()=>{request.current++;setSelected(null)}} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="dialog-top song-close"><button aria-label="關閉歌詞" onClick={close}><X size={22}/></button></div>{selected&&<><div className="detail-heading"><span className="detail-icon"><Music2 size={26}/></span><div><h2>{selected.title}</h2><p>{selected.artist}</p></div></div>{reference&&<div className="playback-reference"><a className="primary" href={reference.url} target="_blank" rel="noopener noreferrer">{reference.label} <ArrowUpRight size={15}/></a><span>{reference.artist}</span>{reference.segmentUrl&&<a href={reference.segmentUrl} target="_blank" rel="noopener noreferrer" className="segment-link">{reference.segmentLabel} <ArrowUpRight size={14}/></a>}</div>}{(selected.note??reference?.note)&&<p className="song-note">{selected.note??reference?.note}</p>}<div className="lyrics-tools"><span>歌詞</span><div><button aria-label="縮小歌詞字體" onClick={()=>setFont(v=>Math.max(14,v-2))}>A−</button><button aria-label="放大歌詞字體" onClick={()=>setFont(v=>Math.min(30,v+2))}>A＋</button><button disabled={!selected.lyrics} onClick={()=>copy(selected.lyrics||'')}><Copy size={14}/> 複製歌詞</button></div></div>{detailLoading?<div className="empty"><LoaderCircle className="spin"/> 正在載入歌詞…</div>:detailError?<div className="empty"><p>{detailError}</p><button className="primary" onClick={()=>open(selected)}>重試</button></div>:selected.lyrics?<div className="lyrics-text" style={{fontSize:font}}>{selected.lyrics}</div>:<div className="empty missing-lyrics"><p>這首歌還未加入歌詞</p></div>}{admin&&!detailLoading&&!detailError&&<div className="detail-actions"><button className="secondary" onClick={()=>edit(selected)}><Pencil size={15}/> 編輯歌曲</button><button className="danger" disabled={busy} onClick={()=>remove(selected)}><Trash2 size={15}/> 刪除歌曲</button></div>}</>}</dialog>
 <dialog ref={loginDialog} className="editor-dialog" onCancel={()=>{setLoginError('');setLoginPassword('')}}><div className="dialog-top"><span className="eyebrow">ADMIN LOGIN</span><button type="button" aria-label="關閉登入" onClick={()=>{loginDialog.current?.close();setLoginError('')}}><X size={22}/></button></div><form onSubmit={login}><h2>歌曲管理</h2><p className="form-hint">請輸入管理密碼</p><label>管理密碼<input type="password" autoComplete="current-password" autoFocus required value={loginPassword} onChange={e=>setLoginPassword(e.target.value)}/></label>{loginError&&<p className="url-hint" role="alert">{loginError}</p>}<div className="form-bottom"><span>登入後即可管理曲庫</span><button className="primary" disabled={loginBusy} type="submit">{loginBusy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {loginBusy?'登入中…':'進入管理'}</button></div></form></dialog>
 <dialog ref={editor} className="editor-dialog" onCancel={()=>{if(busy) return;setEditing(null)}}><div className="dialog-top"><span className="eyebrow">SONG EDITOR</span><button disabled={busy} aria-label="關閉編輯" onClick={()=>{editor.current?.close();setEditing(null)}}><X size={22}/></button></div>{editing&&<form onSubmit={save}><h2>{editing.id?'編輯歌曲':'新增歌曲'}</h2><p className="form-hint">把喜歡的歌，放進你的歌庫。</p><div className="form-row"><label>歌名<input required maxLength={150} autoFocus value={editing.title} placeholder="輸入歌曲名稱" onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>歌手<input required maxLength={150} value={editing.artist} placeholder="輸入歌手名稱" onChange={e=>setEditing({...editing,artist:e.target.value})}/></label></div><label>YouTube 網址 <small>選填</small><input type="url" maxLength={2048} value={editing.youtube_url||''} placeholder="https://www.youtube.com/watch?v=…" onChange={e=>setEditing({...editing,youtube_url:e.target.value})}/>{editing.youtube_url&&!youtubeUrl(editing.youtube_url)&&<small className="url-hint">請貼上有效的 YouTube 影片網址</small>}</label><label>備註 <small>選填 · 版本說明或提醒</small><textarea className="note-input" maxLength={500} value={editing.note||''} placeholder="輸入備註…" onChange={e=>setEditing({...editing,note:e.target.value})}/></label><label>歌詞 <small>可稍後補上 · 保留換行</small><textarea maxLength={500} value={editing.lyrics||''} placeholder="在這裡貼上或輸入歌詞…" onChange={e=>setEditing({...editing,lyrics:e.target.value})}/></label><div className="form-bottom"><span>{(editing.lyrics||'').length.toLocaleString()} / 500 字</span><button className="primary" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {busy?'儲存中…':'儲存歌曲'}</button></div></form>}</dialog>
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}</>
}
